### ISSUE TITLE
Package for conda forge

### ISSUE THREAD

**Issue by jtpio** [manics/jupyter-offlinenotebook#154]
Opening the issue here, but the packaging would be done in https://github.com/conda-forge/staged-recipes

It would be nice if `jupyter-offlinenotebook` could be made available on conda forge too.

It looks like this would make it possible to list `jupyter-offlinenotebook` as part of the environment in the `repo2docker` buildpack directly?

https://github.com/jupyterhub/repo2docker/blob/560b1d96a0e39cb8de53cb41a7c2d8d23384eb82/repo2docker/buildpacks/conda/environment.yml#L2-L9

**Comment by manics** [comment]
It's already in conda-forge thanks to @xhochy :smile: https://github.com/jupyterhub/repo2docker/pull/846
Based on that discussion it sounds like switching from pip to conda when we switch to JupyterLab 3 package makes sense. I'll release 0.2.0 to pypi, update and test the [feedstock](https://github.com/conda-forge/jupyter-offlinenotebook-feedstock), and let you know!

**Comment by jtpio** [comment]
Perfect, thanks!

**Comment by jtpio** [comment]
Closing, and we can switch to installing it from conda in `repo2docker` then.
