### ISSUE TITLE
Confirm overwriting the notebook before doing it?

### ISSUE THREAD

**Issue by betatim** [manics/jupyter-offlinenotebook#17]
Should the "load from your browser" button first ask the user if they want to overwrite their notebook? The last time I tested it I was surprised that the popup I got said "congrats we've updated the notebook" instead of "Do you want to overwrite your notebook? Yes/No"

**Comment by manics** [comment]
Could do, was trying to avoid too many dialogs! Ideally I think a dialog to confirm followed by a status message somewhere would be best, but I don't know how to do the latter.

**Comment by betatim** [comment]
"status message" == a snackbar or some other notification that displays for a bit and then goes away?

I like the idea, but I also don't know where in the Jupyter ~~docs~~ code to look to find out :-/
